# Generated by Django 2.1.7 on 2019-03-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user',
            new_name='User',
        ),
    ]
