# Generated by Django 2.1.7 on 2019-03-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20190310_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='User',
            new_name='user',
        ),
    ]
