# Generated by Django 2.1.7 on 2019-03-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20190310_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='type',
            new_name='user_type',
        ),
    ]
