# Generated by Django 2.1.7 on 2019-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='c_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='emp_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='product',
            new_name='product_id',
        ),
    ]
