# Generated by Django 2.1.7 on 2019-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190405_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='product_id',
            new_name='product',
        ),
    ]
